PEN_MENU_ENTRY_NAME = 'pen'

LINE_COLOR_PROPERTY_NAME = 'line_color'
LINE_WIDTH_PROPERTY_NAME = 'line_width'
POINTS = 'points'

LINE_COLOR_PROPERTY_DESC = 'Цвет линии'
LINE_WIDTH_PROPERTY_DESC = 'Толщина линии'

EMPTY_DESC = ''
